apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-lab-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
    - name: app.health
      interval: 30s
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total{namespace=~"apps|apps-staging"}[10m]) * 60 > 3
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "Pod {{ $labels.pod }} is crash-looping"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} restarted more than 3 times in 10m."

        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_spec_replicas{namespace=~"apps|apps-staging"} != kube_deployment_status_available_replicas{namespace=~"apps|apps-staging"}
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "Deployment {{ $labels.deployment }} has unavailable replicas"
            description: "{{ $labels.namespace }}/{{ $labels.deployment }} has unavailable replicas."

        - alert: PodNotReady
          expr: kube_pod_status_phase{namespace=~"apps|apps-staging", phase=~"Pending|Unknown"} > 0
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "Pod {{ $labels.pod }} is not ready"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been non-ready for 5 minutes."

    - name: resource.pressure
      interval: 60s
      rules:
        - alert: NodeHighMemoryPressure
          expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.1
          for: 5m
          labels:
            severity: critical
            team: platform
          annotations:
            summary: "Node {{ $labels.instance }} memory < 10% free"
            description: "Node {{ $labels.instance }} has less than 10% memory available."

    - name: kyverno.policy
      interval: 60s
      rules:
        - alert: KyvernoPolicyViolation
          expr: increase(kyverno_policy_results_total{rule_result="fail"}[5m]) > 0
          for: 0m
          labels:
            severity: warning
            team: security
          annotations:
            summary: "Kyverno policy violation"
            description: "Policy {{ $labels.policy_name }} had violations in the last 5m."

        - alert: KyvernoHighViolationRate
          expr: sum(rate(kyverno_policy_results_total{rule_result="fail"}[10m])) > 1
          for: 5m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "High rate of Kyverno policy violations"
            description: "More than 1 violation/s over the last 10 minutes."
